### ISSUE TITLE
Not able to install requirements

### ISSUE THREAD

**Issue by stbkde** [qrioniclabs/homeassistant-mysql_command#5] opened 2023-05-11 06:53 UTC
Platform error notify.mysql_command - Requirements for mysql_command not found: ['mysql-connector-python==8.0.32'].

`Unable to install package mysql-connector-python==8.0.32: ERROR: Cannot install mysql-connector-python==8.0.32 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.1 -> 23.1.2 [notice] To update, run: pip install --upgrade pip`

Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1

**Comment by milanov8** [comment] 2023-05-12 18:30
same here

Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1

**Comment by maxalbani** [comment] 2023-05-15 11:09
same problem...

**Comment by qrioniclabs** [comment] 2023-05-15 11:28
Hi! Thanks for opening this issue! I will test this and post back here with a fix soon.

**Comment by qrioniclabs** [comment] 2023-05-16 22:07
I am unable to reproduce this problem right now. I removed and reinstalled the integration without any problems in my setup:

Home Assistant 2023.5.3
Supervisor 2023.04.1
Operating System 10.1

One thing I would like you to test is the "requirements" parameter in manifest.json. Could somebody download the archive and install it the manual way but change line 7 of manifest.json from 

`"requirements": ["mysql-connector-python==8.0.32"], `
to
`"requirements": ["mysql-connector-python"], `

??

Please try and report back. Thanks!

**Comment by milanov8** [comment] 2023-05-17 13:34
Hi,
changed
"requirements": ["mysql-connector-python==8.0.32"], 
to
"requirements": ["mysql-connector-python"], 

but same issue
thx

**Comment by maxalbani** [comment] 2023-05-17 14:29
> I am unable to reproduce this problem right now. I removed and reinstalled the integration without any problems in my setup:
> 
> Home Assistant 2023.5.3 Supervisor 2023.04.1 Operating System 10.1
> 
> One thing I would like you to test is the "requirements" parameter in manifest.json. Could somebody download the archive and install it the manual way but change line 7 of manifest.json from
> 
> `"requirements": ["mysql-connector-python==8.0.32"], ` to `"requirements": ["mysql-connector-python"], `
> 
> ??
> 
> Please try and report back. Thanks!

Changed "requirements": ["mysql-connector-python==8.0.32"] => "requirements": ["mysql-connector-python"].
Restart home assistant and the integration is working properly again.

So, at this point, I think it's enough to release a new version with the new manifest.json.

Thank you!

**Comment by maxalbani** [comment] 2023-05-17 14:30
> Hi, changed "requirements": ["mysql-connector-python==8.0.32"], to "requirements": ["mysql-connector-python"],
> 
> but same issue thx

After editing the manifest.json file you need to restart home assistant for the change to take effect.

**Comment by qrioniclabs** [comment] 2023-05-20 14:29
Thank you, @maxalbani!
I fixed it in release 1.1.1
Closing this issue now.

**Closed as completed** 2023-05-30 17:03 UTC
